"""add meetings table

Revision ID: a18ab4ab5fdf
Revises: 10d3d84e7133
Create Date: 2025-04-27 14:47:11.740145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18ab4ab5fdf'
down_revision: Union[str, None] = '10d3d84e7133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('meeting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('participants', sa.Text(), nullable=False),
    sa.CheckConstraint("location <> ''", name='check_location_non_empty'),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    # ### end Alembic commands ###